parameters:
    database_path:     %kernel.root_dir%/sqlite.db
    database_driver:   pdo_sqlite

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
