dschini_blog_rest:
    resource: "@DschiniBlogRestBundle/Resources/config/routing.yml"
    prefix:   /api

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc
